# Generated by Django 5.1.5 on 2025-01-31 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_alter_endereco_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='carrinho',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
